# Generated by Django 6.0 on 2026-01-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_initialized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DBConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL')], default='postgres', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('database_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.TextField()),
                ('schema', models.CharField(default='public', help_text='Database schema to inspect', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_connection', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_tables', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('generated_metadata', models.JSONField()),
                ('approved_metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='app.project')),
            ],
            options={
                'unique_together': {('project', 'table_name')},
            },
        ),
    ]
