# Generated by Django 6.0 on 2026-01-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=150)),
                ('audience', models.CharField(max_length=150)),
                ('purpose', models.TextField()),
                ('focus_areas', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('outline_generated', 'Outline Generated'), ('outline_approved', 'Outline Approved')], default='outline_generated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outline_json', models.JSONField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outline', to='app.report')),
            ],
        ),
    ]
