# Generated by Django 6.0 on 2026-01-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_topiccontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccontent',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='iteration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topiccontent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('generated', 'Generated'), ('approved', 'Approved')], default='draft', max_length=30),
        ),
    ]
