# Generated by Django 6.0 on 2026-01-19 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_report_reportoutline'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsectionTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('subsection_title', models.CharField(max_length=255)),
                ('topics_json', models.JSONField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsection_topics', to='app.report')),
            ],
        ),
    ]
