# Generated by Django 6.0 on 2026-01-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subsectiontopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='outline_approved',
            field=models.BooleanField(default=False),
        ),
    ]
