# Generated by Django 6.0 on 2026-02-04 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_topiccontent_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('generated', 'Generated'), ('approved', 'Approved')], default='draft', max_length=30)),
                ('content_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='app.subsection')),
            ],
        ),
    ]
