# Generated by Django 6.0 on 2026-03-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_sectioncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsection',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
