# Generated by Django 6.0 on 2026-03-26 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_subsection_is_generating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_scores', models.JSONField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='app.report')),
            ],
        ),
        migrations.CreateModel(
            name='TopicEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.JSONField()),
                ('issues', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_evaluations', to='app.report')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='app.topic')),
            ],
            options={
                'unique_together': {('topic', 'report')},
            },
        ),
    ]
