# Generated by Django 6.0 on 2026-04-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_subsectiongeneratetime_topicgeneratetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicReadability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flesch_kincaid_grade', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readability_scores', to='app.report')),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='readability', to='app.topic')),
            ],
        ),
    ]
