# Generated by Django 6.0 on 2026-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_topicreadability'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicevaluation',
            name='geval_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topicevaluation',
            name='geval_overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicevaluation',
            name='geval_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topicevaluation',
            name='geval_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
