# Generated by Django 6.0 on 2026-04-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_topicevaluation_geval_issues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicevaluation',
            name='issues',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicevaluation',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicevaluation',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicevaluation',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
